name: CI

on:
  pull_request:
  push:
    branches:
      - master

env:
  uv-version: "0.11.3"

jobs:
  test:
    strategy:
      matrix:
        platform:
          # Compile against oldest available Ubuntu to get an older glibc
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - macos-15-intel
          - macos-15
          - windows-2025
        python:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.uv-version }}
          enable-cache: true
          cache-suffix: test
      - name: Install dependencies
        run: uv sync --locked --only-group nox
      - name: Test
        run: uv run --no-sync nox -s test-${{ matrix.python }}
      - name: Test Polars
        run: uv run --no-sync nox -s test_polars-${{ matrix.python }}
      - name: Test Pandas
        run: uv run --no-sync nox -s test_pandas-${{ matrix.python }}
      - name: Store coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.platform }}-${{ matrix.python }}
          path: |
            python.*.lcov
            rust.*.lcov
          if-no-files-found: error

  coverage:
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install lcov
        run: sudo apt-get update && sudo apt-get install -y lcov
      - name: Fetch coverage
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-*
          merge-multiple: true
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.uv-version }}
          enable-cache: true
          cache-suffix: coverage
      - name: Install dependencies
        run: uv sync --locked --only-group nox
      - name: Combine coverage
        run: uv run --no-sync nox -s coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: combined.lcov
          fail_ci_if_error: true

  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-key: lint
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.uv-version }}
          enable-cache: true
          cache-suffix: lint
      - name: Install dependencies
        run: uv sync --locked --only-group nox
      - name: Run code quality checks
        run: uv run --no-sync nox -s lint
