name: Release

on:
  push:
  #   tags:
  #     - 'v*'

env:
  python-version: "3.10"
  poetry-version: "1.6.1"

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-22.04
    environment: release
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry==${{ env.poetry-version }}
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}
      - name: Build release
        run: poetry build
      - run: ls -al dist
      # - name: Upload to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
